### ISSUE TITLE
Connect via Web adress

### ISSUE THREAD

**Issue by inv4der** [jjg/octowatch#15]
Hi, I'm trying to connect the app via example.com and I can't, even though I can access Octoprint.  The app only works in the same network with the ip of Octoprint. Should I be able to connect this way?

**Comment by frankvdh** [comment]
Trying to connect to Octoprint running on Raspberry Pi (Octopi) using octopi.local:5000 but not succeeding. Is the API key case-sensitive? Phone (Galaxy S3) is on the same LAN as the Pi. Octopi is configured to not use any security.

I think it would be helpful if the Android end of the app attempted a connection to Octoprint when you press 'Save', and display success/failure status.

**Comment by jjg** [comment]
Are you able to open http://octopi.local:5000 in the phones web browser and see the Octoprint web interface?

**Comment by frankvdh** [comment]
Hi Jason,
I can't get to the web page from my phone's browser when I go by name, but
192.168.1.70:5000 works.

Now I've changed octowatch to use the IP address, it's working fine, thanks.

Frank

**Comment by jjg** [comment]
Awesome @frankvdh, very happy to hear it!

I'll close this issue for now but feel free to re-open if you have other connectivity-related issues.
