### ISSUE TITLE
Buzz when complete

### ISSUE THREAD

**Issue by frankvdh** [jjg/octowatch#20]
When the print is complete, send a buzz plus notification to the watch

**Comment by jjg** [comment]
Hi @frankvdh,

You should get a notification when printing is complete (it doesn't come immediately, usually within a minute after the print finishes).  Is that not working?

Here's the code the fires the notification: https://github.com/jjg/octowatch/blob/master/src/js/pebble-js-app.js#L71

Let me know if you're not seeing that, thanks!

**Comment by frankvdh** [comment]
Hi Jason

My mistake sorry. I hadn't included octowatch in the list of apps allowed
to send notifications. It's all good now.

Frank

Hi @frankvdh <https://github.com/frankvdh>,

You should get a notification when printing is complete (it doesn't come
immediately, usually within a minute after the print finishes). Is that not
working?

Here's the code the fires the notification:
https://github.com/jjg/octowatch/blob/master/src/js/pebble-js-app.js#L71

Let me know if you're not seeing that, thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/jjg/octowatch/issues/20#issuecomment-73238813>.

**Comment by jjg** [comment]
Excellent, I'm glad to hear it's working now @frankvdh!
